# Change these first
owner: allertafvg # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: Allerta FVG API 1
    url: $SECRET_API1
    expectedStatusCodes:
    - 200
  - name: Allerta FVG API 2
    url: $SECRET_API2
    expectedStatusCodes:
    - 200
  - name: Map Server
    url: $SECRET_SITE
  - name: Mapbox Tiles Server
    url: https://api.mapbox.com/styles/v1/mapbox/streets-v11/tiles/256/
    expectedStatusCodes:
    - 401

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.allertafvg.eu.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/allertafvg/allertafvg.github.io/master/images/logo.png
  name: Allerta FVG Status
  introTitle: "**Status Page** Allerta FVG"
  introMessage: List of status of Allerta FVG services
  themeUrl: http://allertafvg.eu.org/static/italia.css
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
