# Change these first
owner: allertafvg # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: Allerta FVG Website
    url: https://allertafvg.eu.org
  - name: Map Server
    url: $SECRET_SITE
  - name: Mapbox Tiles Server
    url: https://api.mapbox.com/styles/v1/mapbox/streets-v11/tiles/256/

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: allertafvg.eu.org/status
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/allertafvg/allertafvg.github.io/master/images/logo.png
  name: Allerta FVG Status
  introTitle: "**Status Page** Allerta FVG"
  introMessage: List of status of Allerta FVG services
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
